version: '3'
services:
    v2ray_tls:
        build:
          context: ./
          dockerfile: Dockerfile
          args:
            panelurl: api_url
            panelkey: api_key
            nodeid: node_number
            downwithpanel: 1
            speedtestrate: 6 
            paneltype: 0 
            usemysql: 0
            LDNS: 8.8.8.8
            nodeurl: node_host
            mail: mail_for_caddy
            fakeurl: https://ctftime.org/
            v2ray_path: v2ray
            v2ray_port: 10550
        ports: 
            - 443:443
            - 80:80
        privileged: true
        restart: always
        extra_hosts:
          - "auth.rico93.com:127.0.0.1"
        logging: 
            driver: "json-file"
            options: 
              max-size: "10m"
              max-file: "1"
